// /datum/quirk/blooddeficiency
// 	species_whitelist = list(SPECIES_AKULA, SPECIES_AQUATIC, SPECIES_DWARF,
// 	SPECIES_HUMANOID, SPECIES_INSECT, SPECIES_MAMMAL, SPECIES_PODPERSON_WEAK, /*SPECIES_SYNTH*/,
// 	SPECIES_SLIMESTART, SPECIES_SKRELL, SPECIES_TAJARAN, SPECIES_UNATHI, SPECIES_VOX, SPECIES_VOX_PRIMALIS,
// 	SPECIES_VULP, SPECIES_XENO, SPECIES_GHOUL, SPECIES_TESHARI, SPECIES_HEMOPHAGE, SPECIES_FELINE_PRIMITIVE)
